import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <nav className={`flex justify-center w-full gap-3`}>
            <h1 className={`text-3xl`}><Link href={`/main`}>Main</Link></h1>
            <h1 className={`text-3xl`}><Link href={`/todo`}>TodoList</Link> </h1>
        </nav>
        {children}
        </body>
        </html>
    );
}
